{% set name = "mdanalysis-sphinx-theme" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mdanalysis_sphinx_theme-{{ version }}.tar.gz
  sha256: 99c25d9310531f2996a61ad2b06d4ffe5ea8d1e476a851df68c4ff7a50049a87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - beautifulsoup4
    - css-html-js-minify
    - libsass
    - lxml
    - python-slugify
    - sphinx >=6.2.1,<7.0
    - sphinx_rtd_theme >=1.2


test:
  imports:
    - mdanalysis_sphinx_theme
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/MDAnalysis/mdanalysis-sphinx-theme
  summary: 'A Sphinx Theme for MDAnalysis'
  description: |
    This is a Sphinx theme for MDAnalysis. It is a modification of
    `sphinx_rtd_theme` based on
    `msmb_theme` and `openff-sphinx-theme`.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://mdanalysis-sphinx-theme.readthedocs.io/en/latest/
  dev_url: https://github.com/MDAnalysis/mdanalysis-sphinx-theme

extra:
  recipe-maintainers:
    - orbeckst
    - IAlibay
    - lilyminium
